### ISSUE TITLE
Cannot delete the exec_directory in the epilogue

### ISSUE THREAD

**Issue by jgaida** [oar-team/cigri#35]
The exec_directory cannot be deleted in the epilogue. I get the following error:
~~~
15420: (open) EPILOG_EXIT_ERROR of job 849 at 2016-03-11T10:50:34+01:00 on lyon
The job exited with exit status 256;
~~~~

I believe this is because the output file of the epilogue job is stored in this directory. 
Deleting the exec_directory after a campaign is rather useful when we would like to clean all output/temporary files of a campaign.

This issue has connections with #5 but even with a gridclean command, this issue should be fixed.

Example:
~~~
{
  "name": "Povray Landscape",  

  "resources": "nodes=1", 
  "walltime": "00:30:00", 
  "exec_file": "~/cigri/pov/pov.sh",
  "exec_directory": "$HOME/cigri/pov-tmp/",

  "nb_jobs": 4,

  "clusters": {   
    "lyon": {}
  },

  "epilogue": [
    "rm -rf ~/cigri/pov-tmp/"
  ]

}
~~~

**Comment by bzizou** [comment]
I think that the epilogue should be run from the home directory, like the prologue for a similar reason (the prologue is often used to create the working directory).
