### ISSUE TITLE
Macro variables in the JDL

### ISSUE THREAD

**Issue by bzizou** [oar-team/cigri#7]
Some variables should be available into the JDL file, maybe as macro (%HOME%, %CAMPAIGN_ID%,...). The special case of the $HOME variable should be examined (HOME of the grid frontend or of the cluster? using a macro could be more easy for users than having to escape it with several backslashes)

**Comment by jgaida** [comment]
I'm not sure why escape characters have to be used for variables or directories. Some JDL examples does not use escape characters.

**Comment by bzizou** [comment]
Fixed by 72f13283923d3a26da70f8e0240ca6b24b7183ad
